"""
Django settings for globalvision project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

SECRET_KEY = 'django-insecure-_1we)s1zulop&+tj_&!d_2l&f&8@354$pl*@!$rew8e301kf+p'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'inventory',
    'blog',
    'contacts',
    'cms',
    'bookings',
    'cart',
    'django_summernote',
    'user_dashboard',
    'notifications',
]

AUTH_USER_MODEL = 'account.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'globalvision.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'globalvision.wsgi.application'


# Database (PostgreSQL Configuration)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'globalvision',
        'USER': 'postgres',
        'PASSWORD': 'Ayush',
        'HOST': '127.0.0.1',
        'PORT': '5432', 
    }
}

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication redirects
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'account:login'

SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '400px',
        'toolbar': [
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['font', ['strikethrough']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['insert', ['link', 'picture']],
            ['view', ['fullscreen', 'codeview']],
        ],
    }
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'visiong546@gmail.com'
EMAIL_HOST_PASSWORD = 'rsjoswudftoxqcpp'
DEFAULT_FROM_EMAIL = f'GlobalVision <{EMAIL_HOST_USER}>'

# Unfold Admin Configuration
UNFOLD = {
    "SITE_HEADER": "Global Vision Admin",
    "SITE_TITLE": "Global Vision Admin",
    "SITE_SYMBOL": "explore_nearby",  
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "37 99 235",  # Slightly more professional blue
            "600": "29 78 216",
            "700": "30 64 175",
            "800": "30 58 138",
            "900": "23 37 84",
            "950": "15 23 42",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Platform Core",
                "items": [
                    {
                        "title": "Vehicles",
                        "icon": "directions_car",
                        "link": "/admin/inventory/vehicle/",
                    },
                    {
                        "title": "Equipments",
                        "icon": "hiking",
                        "link": "/admin/inventory/equipment/",
                    },
                    {
                        "title": "Reservations",
                        "icon": "calendar_month",
                        "link": "/admin/bookings/booking/",
                    },
                    {
                        "title": "Blog Editorial",
                        "icon": "auto_stories",
                        "link": "/admin/blog/blogpost/",
                    },
                ],
            },
            {
                "title": "Communications",
                "items": [
                    {
                        "title": "Inbound Queries",
                        "icon": "mail",
                        "link": "/admin/contacts/contactmessage/",
                    },
                ],
            },
            {
                "title": "System Settings",
                "items": [
                    {
                        "title": "Access Control",
                        "icon": "security",
                        "link": "/admin/account/user/",
                    },
                    {
                        "title": "Static Pages",
                        "icon": "web_stories",
                        "link": "/admin/cms/aboutpage/",
                    },
                ],
            }
        ],
    },
}

# eSewa Payment Settings
ESEWA_SECRET_KEY = '8gBm/:&EnhH.1/q'
ESEWA_PRODUCT_CODE = 'EPAYTEST'
ESEWA_PAYMENT_URL = 'https://rc-epay.esewa.com.np/api/epay/main/v2/form'
ESEWA_VERIFICATION_URL = 'https://rc-epay.esewa.com.np/api/epay/transaction/status/'
