# Generated by Django 5.2.5 on 2026-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_cart_id_alter_cartitem_id_alter_equipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('gear', 'Trekking Gear'), ('clothing', 'Outdoor Clothing'), ('essentials', 'Trekking Essentials')], max_length=20),
        ),
    ]
