# Generated by Django 5.2.5 on 2026-03-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
