# Generated by Django 5.2.5 on 2026-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Off-Road', 'Off-Road'), ('Vans', 'Vans')], default='Luxury', max_length=20),
        ),
    ]
