# Generated by Django 6.0.1 on 2026-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Off Road', 'Off Road'), ('Vans', 'Vans')], default='Luxury', max_length=20),
        ),
    ]
