# Generated by Django 5.2.5 on 2026-04-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
