# Generated by Django 5.2.5 on 2026-04-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
